### ISSUE TITLE
IIS Trying to load Admin Static Assets from Local Nuget folder 

### ISSUE THREAD

**Issue by Dandroid5000** [Geta/geta-notfoundhandler#10]
Hi,

When I run my site on my local machine in IIS, I get a 'DirectoryNotFoundException'.

![image](https://user-images.githubusercontent.com/96799065/147611322-4df7a300-434e-4db8-8e59-b235a41891e3.png)

Why is the site trying to serve assets from my local nuget folder? I can grant permissions to this directory and it loads... but this solution will not be possible when the site is later deployed into production.

Should I be able to move these static assets into my solution and specify the path somehow in config? Note, I've tried specifying the path via clientResourceRelativePath in the modules.config but it does not seem to respect the value I pace here.

Any help would be greatly appreciated

Thanks in advance
Dan

**Comment by valdisiljuconoks** [comment]
Static web assets are part of Razor Class Library (RCL) project. It's "normal" that VS/IIS tries to load those from NuGet cache.

Package assets are copied to `wwwroot` dir (`wwwroot\_content\{package-id}`) once the project is published (which should be one of the last steps in your CI/CD pipeline).

More info - https://docs.microsoft.com/en-us/aspnet/core/razor-pages/ui-class?view=aspnetcore-6.0&tabs=visual-studio#publish-1

**Comment by Dandroid5000** [comment]
Thanks for the  quick reply @valdisiljuconoks .
Yep, I can see the files in wwwroot after publish. 
Thanks for your help
Cheers
Dan
