### ISSUE TITLE
Time out on suggestions/Not able to delete suggestions

### ISSUE THREAD

**Issue by QuirijnLangedijk** [Geta/geta-notfoundhandler#107]
Hi,

The suggestions page for one of our projects has grown so large that it's become impossible to load the page before Cloudflare times out.
I thought that using the 'delete all suggestions' button in the settings would fix the issue, but it looks like the delete times out before deleting everything, since the page still times out after trying to delete 5+ times.
By making a local copy of the db, I was able to find out that there are over 2 million suggestions, and while I added some redirects to stop it filling up so fast, Im still not able to clean all suggestions.

Is there any fix/workaround for this?

EDIT:

We ended up asking Optimizely to empty the entire table, since the 'delete all suggestions' didn't seem to do anything

**Comment by mzleslie** [comment]
Anyone else run across this and have an idea on how to fix? We are encountering the same issue with millions of rows in suggestion and unable to delete.

**Comment by kimjust6** [comment]
We are having the same issue...except we have 10 million entries. -_-.
I suppose we will also have to ask Optimizely to empty the table.
