### ISSUE TITLE
Import as permanent redirect

### ISSUE THREAD

**Issue by performingmonkey** [Geta/geta-notfoundhandler#115]
We are planning to use the import process to import over a thousand redirects in an xml file. This mostly seems to be working, however these are all imported as temporary redirects. Is there anyway to set the imported redirects as 301s?

**Comment by tmedina-clari** [comment]
Would love to know if this is possible as well.

**Comment by performingmonkey** [comment]
Hey Therese, 

Yeah I managed to figure it out in the end.  You can add the redirect type in as an Attribute on the 'old' tag.  Example below.

`<url>
<old redirectType="Permanent">/about-us/annual-reports/</old>
<new>/about/strategic-documents/</new>
</url>`

**Comment by tmedina-clari** [comment]
> Hey Therese,
> 
> Yeah I managed to figure it out in the end. You can add the redirect type in as an Attribute on the 'old' tag. Example below.
> 
> `<url> <old redirectType="Permanent">/about-us/annual-reports/</old> <new>/about/strategic-documents/</new> </url>`

Awesome, this worked for me too. Thank you!
