### ISSUE TITLE
Feature request: Sortable headers in the Redirects tab

### ISSUE THREAD

**Issue by ArildHenrichsen** [Geta/geta-notfoundhandler#117]
It would be useful to be able to click the "Old URL", "New URL", "Wildcard" and "Redirect Type" headers to toggle between ascending/descending sorting of the table.

**Comment by ArildHenrichsen** [comment]
@ellinge Perfect, thanks!

**Comment by ellinge** [comment]
I’m not part of Geta /  so it’s up to them
