### ISSUE TITLE
Set permanent as default redirect configuration

### ISSUE THREAD

**Issue by KerckhofEmiel** [Geta/geta-notfoundhandler#118]
I was wondering if it is possible to configure somewhere that the default redirect type configuration should be permanent instead of temporary?

![image](https://github.com/Geta/geta-notfoundhandler/assets/35845628/c0b8daf4-1759-4867-9d25-7c472e2111e3)

@marisks @valdisiljuconoks @kaspars-ozols @jevgenijsp @ellinge

**Comment by ellinge** [comment]
No it’s set as selected in template:
https://github.com/Geta/geta-notfoundhandler/blob/2ed3c5f746d5497fd9f0a6432aa453935e2b8a9e/src/Geta.NotFoundHandler.Admin/Areas/GetaNotFoundHandlerAdmin/Pages/Index.cshtml#L48

**Comment by ArildHenrichsen** [comment]
I agree that it would be beneficial to be able to specify default redirect type in configuration.
Changing the HTML template is not good as it would break potential future package upgrades.
