### ISSUE TITLE
Optimizely CMS times out after a deployment due to a query 

### ISSUE THREAD

**Issue by so-huz** [Geta/geta-notfoundhandler#121]
CMS site with cms12 , .Net 8 and Notfoundhandler version 5.0.8 is getting timed out due to a query that is consuming the sql sever at 100%. 

``` sql 
(@contentKey nvarchar(2000))SELECT TOP 1 Id, ContentKey, Urls, CreatedUtc 
                                FROM [dbo].[NotFoundHandler.ContentUrlHistory] 
                                WHERE ContentKey = @contentKey 
                                ORDER BY CreatedUtc DESC
```

And also we noticed that 3000+ records are getting added to the table `ContentUrlHistory` each day. 
Is this normal ? 
Can we clean the table ? 
Anyone else facing similar issue ? 

The table currently has 500,000 + records.

**Comment by pmatocha** [comment]
We are experiencing the same issue on our testing enviroment. cms12.2, .Net 6.0 and Notfoundhandler version 5.0.8

Our table has 1592718 records. And it keeps getting bigger and bigger.

Is it possible to add some maintance, for example add OnDeletedContent event to remove records?

**Comment by so-huz** [comment]
@pmatocha Perhaps a job that modifies content _**could be**_ adding unwanted records to this table. We asked support to delete such records (around 500,000) and the time out issue went away. 

But the underlying issue is still there and the table keeps growing back.

**Comment by jevgenijsp** [comment]
Issue resolved by adding index in ContentUrlHistory table in the latest release https://github.com/Geta/geta-notfoundhandler/releases/tag/v5.0.9
