### ISSUE TITLE
Sandbox App Broken

### ISSUE THREAD

**Issue by jaymarvels** [Geta/geta-notfoundhandler#125]
Has anyone else found that the sandbox app is really janky?

Trying to add some new features to contribute but just getting the sandbox foundation to run is a headache. Missing build scripts, missing files in the App_data.

Finally got them sorted and now there is an issue with the MenuProvider where it cannot find the correct module:

```
ArgumentException: Unable to find a module by assembly 'Geta.NotFoundHandler.Optimizely,

Geta.NotFoundHandler.Optimizely.MenuProvider.GetMenuItems() in MenuProvider.cs
+
            var url = Paths.ToResource(GetType(), "container");
System.Linq.Enumerable+SelectManySingleSelectorIterator<TSource, TResult>.MoveNext()
```

Would love to contribute as its open source, but come on, it needs to be working at point of cloning.

**Comment by jevgenijsp** [comment]
I've upgraded the sandbox to the latest Foundation version.
With the latest version, everything is going smoothly for me.

https://github.com/Geta/geta-notfoundhandler/pull/141
