### ISSUE TITLE
Build warning

### ISSUE THREAD

**Issue by lars-w-pedersen** [Geta/geta-notfoundhandler#2]
After installing Geta.NotFoundHandler.Optimizely 1.0.0-rc i get the following warning when building:

Geta.NotFoundHandler.Optimizely 1.0.0-rc depends on Geta.NotFoundHandler.Admin (>= 1.0.0-rc) but Geta.NotFoundHandler.Admin 1.0.0-rc was not found. An approximate best match of Geta.NotFoundHandler.Admin 1.0.0 was resolved.

**Comment by valdisiljuconoks** [comment]
Should be fixed with 1.0.0 release (https://nuget.optimizely.com/package/?id=Geta.NotFoundHandler.Optimizely&v=1.0.0)
