### ISSUE TITLE
Nuget package update?

### ISSUE THREAD

**Issue by palle-mertz-isobar** [Geta/geta-notfoundhandler#20]
We just went live with our website on DXP we have been working on for the past 6 months. 

Noticed the issue from PR #14`is acually a problem. I was aware paying notice to this at the time the issue was open (march). But I can see there has been no update of the nuget packages since January. When are you planning to update them on the Optimizley Feed?

**Comment by marisks** [comment]
That's strange. We have released 1.1.0 version in April. I will re-upload it to Optimizely

**Comment by marisks** [comment]
You are right. The package on Optimizely 1.1.0 is missing. As I said, I will re-upload.

**Comment by marisks** [comment]
Now there is 1.1.0 on nuget.optimizely.com. But there is 1.1.1 too. It has some UI improvements.
