### ISSUE TITLE
What are the scheduled jobs? 

### ISSUE THREAD

**Issue by Dandroid5000** [Geta/geta-notfoundhandler#22]
Hi,

I just noticed these two scheduled jobs in the cms.

![image](https://user-images.githubusercontent.com/96799065/169957374-b1f98111-7563-49ef-a937-1a30d2a81a9b.png)

What are these doing exactly? Should we activate these?

Thanks
Dan

**Comment by marisks** [comment]
Wait for the upcoming blog post :)

**Comment by Dandroid5000** [comment]
Hi @marisks , where can I expect to find the blog post? Thanks

**Comment by marisks** [comment]
You can check docs for now: https://github.com/Geta/geta-notfoundhandler#automatic-redirects
