### ISSUE TITLE
Ignore specific routes?

### ISSUE THREAD

**Issue by AndersHGP** [Geta/geta-notfoundhandler#23]
Hi!

It would be a nice feature to be able to ignore specific routes. In our webapplication we proxy some requests to another API that may deliver 404 responses which we dont want the handler to interfere with. Is there an easy way to accomplish this?

**Comment by marisks** [comment]
How does it interfere?

It handles 404s only if a redirect for that URL is found in the DB

**Comment by AndersHGP** [comment]
@marisks It was fixed with this https://github.com/Geta/geta-notfoundhandler/pull/26 so not an issue anymore.
