### ISSUE TITLE
Exception in handler when response has started

### ISSUE THREAD

**Issue by AndersHGP** [Geta/geta-notfoundhandler#24]
Hi! The middleware throws exception when the response has started when it tries to clear it. I can make a PR if you give me permissions. 

Steps to reproduce: 
HttpContext.Response.HasStarted is true when the middleware executes

**Comment by AndersHGP** [comment]
@valdisiljuconoks  Thanks I created a PR

**Comment by hybrid897** [comment]
Believe I'm seeing the same issue on my side.

![image](https://user-images.githubusercontent.com/52395382/171529339-aa7a0956-ba53-41eb-86d6-7210ae55c189.png)

**Comment by Dandroid5000** [comment]
Hi. Just flagging that we are seeing this error logged frequently also.

**Comment by AndersHGP** [comment]
@Dandroid5000 @hybrid897 release 2.0.0 should solve the issue

**Comment by Dandroid5000** [comment]
Hi @AndersHGP , 
Can you please update the package to also support .Net 5? 
We are not in a position to move to .Net 6 yet as we have other packages stuck in 5.
Thanks
Dan

**Comment by marisks** [comment]
@Dandroid5000 You should be able to run on .NET 6 and use .NET 5 packages.

What packages don't support .NET 6 for you?

P.S. I recommend upgrading to the latest Optimizely (Epi) packages. Recently we found out that older Opti packages had a security hole. Luckily, good people found it out and not the bad guys :)

**Comment by marisks** [comment]
Anyway, this is fixed in 2.0.0. So closing.
