### ISSUE TITLE
Configure methods missing in 2.0.0

### ISSUE THREAD

**Issue by AlexanderCarlstrom** [Geta/geta-notfoundhandler#29]
I just installed Geta.NotFoundHandler.Optimizely version 2.0.0. I tried following the configuration guide but AddNotFoundHandler and AddOptimizelyNotFoundHandler methods are not available in this new version. If I downgrade to 1.1.1 I am able to access the methods and therefor add it to the cms.

**Comment by palle-mertz-isobar** [comment]
I think some namespace refactoring has been done?

I guess it is ok for version 2 ... but I would say moving namespaces is a breaking change and should not have been allowed for 1.0.4

**Comment by AlexanderCarlstrom** [comment]
Hi. Yeah, seems to be some issue with the using statements and namespaces.
![image](https://user-images.githubusercontent.com/36960753/172815915-85b90172-e4be-4208-9204-8a3883aad22a.png)
![image](https://user-images.githubusercontent.com/36960753/172815945-e971bafa-92ef-4b6d-9be7-7d9b168576ed.png)

**Comment by valdisiljuconoks** [comment]
Which runtime your project is targeting?

**Comment by AlexanderCarlstrom** [comment]
.net 5.0 if that's what you meant

**Comment by marisks** [comment]
To use 2.0.0, you need .NET 6
