### ISSUE TITLE
Suggestion data implementation design is flawed

### ISSUE THREAD

**Issue by palle-mertz-isobar** [Geta/geta-notfoundhandler#30]
Performance for the paginated list is very poor. It will quickly show. Our website (which was a migration with new URL structure ... but with many redirect) has now run for approx. 1½ month. We have ~4400 rows returned on GetAllSuggestionCount. For all 4400 it will need to run a "Sub query" to get referrers (count). We have past the point where it now times out on DXP (prod). Locally the query on a fast pc takes more than a minute.

The problem is the way referrer is being queries as a subquery. That means regardless of pagination (which page you want to see) all old URLs are being queried for referrers. For now Suggestions is useless for medium-large sized websites if not regularly cleaned up (delete all suggestions) :)

Suggested solution:
Introduce api endpoint for retrieving referrers and not include referrers in GetAllSummaries(). Clicking on referrers on the list in admin is also not something you do for all rows so the info could be fetched on a need basis.
Endpoint should have the same protection as the admin 

We might be able to contribute ... just clarifying that.

**Comment by palle-mertz-isobar** [comment]
Just created PR. Went for a quick simpler optimization of the existing instead. Getting rid of the multiple subqueries and just fetch all data at once with a single query and then filter the referrers in DataTable instead.

Improvement > 30-50 times faster (from 30 secs on my local to under 1 sec) on suggestion list load.

**Comment by marisks** [comment]
As I remember it was just translated from DDS to raw SQL without any optimizations

Thanks for the improvements!

**Comment by palle-mertz-isobar** [comment]
Well I think at some point it should be refactored for the solution I suggested initially. The fix I did is ok for now (big improvement) but for larger amount of data it will not be enough (I have seen examples of 10Gb+ of suggestion data on the old 404 handler collected through many years :) ).

**Comment by marisks** [comment]
I think paging should be done in SQL and there would be no need for excluding referrers. SQL Server should handle that pretty well even with 10Gb+ data.

**Comment by palle-mertz-isobar** [comment]
Jup also a way to go ... you can avoid joining referrers count query for all. But you still include data that might not be needed. And I think you might need index for that join on OldUrl if it need to perform on a large data set.

**Comment by marisks** [comment]
I will try to publish it today.
If not, then tomorrow.

**Comment by marisks** [comment]
I have uploaded the packages to nuget.org and nuget.optimizely.com Should be available tomorrow.

**Comment by palle-mertz-isobar** [comment]
Very nice thanks ... already pulled.
