### ISSUE TITLE
Suggestions table gets out of control

### ISSUE THREAD

**Issue by kaspars-ozols** [Geta/geta-notfoundhandler#37]
1) After less than 1 month in production, `Suggestions` table has grown to 500 000 records.
2) There should be a way to exclude certain URLs from suggestions, such as health probes (`/episerver/health` or similar).

**Comment by palle-mertz-isobar** [comment]
Oh this is old issue ... but if you put a specific url (no wildcard) on the ignore list it will not go to suggestions table right?

When that is said it would still be nice to be able to configure it from startup.

**Comment by marisks** [comment]
@palle-mertz-isobar I've checked the code and it still adds suggestions to the table even if those are ignored.
I think the best solution would be some Regex rules for suggestions that would allow us to filter out and not store URLs in the table.

**Comment by palle-mertz-isobar** [comment]
oh yeah that is bad then ... especially when you consider that it actually deletes suggestion when you ignore a url (maybe only ignore from the suggestion list)

**Comment by mariajemaria** [comment]
@marisks what is the status for this issue? We are having really slow production because of this. Should we manually flush history as a workaround?

**Comment by mariajemaria** [comment]
Actually, sorry, this is another table - NotFoundHandler.ContentUrlHistory

**Comment by kaspars-ozols** [comment]
I also got issue with NotFoundHandler.ContentUrlHistory overfilling to a point the CPU use on SQL server maxes out. This point was achieved when record count was ~2000000.

The most expensive query reported by Application Insights:

```
(@contentKey nvarchar(2000))SELECT TOP 1 Id, ContentKey, Urls, CreatedUtc 
                                FROM [dbo].[NotFoundHandler.ContentUrlHistory]
                                WHERE ContentKey = @contentKey
                                ORDER BY CreatedUtc DESC
 ```
 
Should possibly consider adding index on ContentKey to make the lookup more efficient when the table has reached certain record count.

**Comment by jevgenijsp** [comment]
1) ContentUrlHistory performance was improved in this PR https://github.com/Geta/geta-notfoundhandler/pull/133 by using the hashed index.
2) For suggestions was fixed ignore logic, now all ignored redirects will not be added in the suggestions table https://github.com/Geta/geta-notfoundhandler/pull/134

Let's close this issue for now.
