### ISSUE TITLE
Redirect Loop when redirect to root

### ISSUE THREAD

**Issue by AndersHGP** [Geta/geta-notfoundhandler#43]
If you redirect with query params to root you will get a redirect loop.

Steps to reproduce
OldUrl: https://localhost/a/b?a=b NewUrl: /

Might be related to #36

@svenrog might be related to your fix?

**Comment by marisks** [comment]
@AndersHGP Could you please give me more info? 

I have just tried and created a redirect OldUrl: /a/b?a=b NewUrl: /
Then I navigated to /a/b?a=b and was redirected to /

**Comment by AndersHGP** [comment]
> @AndersHGP Could you please give me more info?
> 
> I have just tried and created a redirect OldUrl: /a/b?a=b NewUrl: / Then I navigated to /a/b?a=b and was redirected to /

@marisks create the old url without the query-params in the tool. Then insert query params when navigating to the url in the browser.

**Comment by svenrog** [comment]
See if `3.0.1` fixes this issue @AndersHGP.

**Comment by AndersHGP** [comment]
@svenrog Thanks for fast response. Will test it out tomorrow.

**Comment by AndersHGP** [comment]
@svenrog seems to be working as intented. Good work!
