### ISSUE TITLE
Feature Request: Add CSV as an additional Import/Export format

### ISSUE THREAD

**Issue by GeekInTheNorth** [Geta/geta-notfoundhandler#47]
During out onboarding process for new Optimizely Clients, we either receive excel or csv files or our SEO team will create one as part of mapping their previous content onto the new content structure within an Optimizely build.  Where clients have had a significant number of redirects within a given CMS (~10,000) they have also been known to export those redirects in order to review them in a human readable manner.

**Comment by GrahamCarr74** [comment]
This would be a great feature to have, we also have the requirement for a CSV import/export for exactly the same reasons!!

**Comment by marisks** [comment]
Sounds as a good feature request.

**Comment by jaymarvels** [comment]
I added a PR that  supports this - https://github.com/Geta/geta-notfoundhandler/pull/126
