### ISSUE TITLE
Update jquery and bootstrap versions in Geta.NotFoundHandler.Optimizely's _ShellLayout.cshtml

### ISSUE THREAD

**Issue by ljvictorio** [Geta/geta-notfoundhandler#50]
The razor file _ShellLayout.cshtml has hard coded references to jQuery-3.2.1.slim.min.js and bootstrap-4.0.0, both of which have CVE's identified. Is it possible to update these libraries to more recent versions (jquery 3.6.1/bootstrap 5)?

**Comment by marisks** [comment]
@ljvictorio What is CVE?

**Comment by breizh22** [comment]
Is there a way to not use this urls for this files. 
Otherwise the CSP has to have these i the white list. 
That's not ideal from a safety point of view.
