### ISSUE TITLE
Issue while updating an existing 301 redirect.

### ISSUE THREAD

**Issue by Anish-Peethambaran** [Geta/geta-notfoundhandler#51]
I observed that when I update an existing 301 redirect in NotFound handler in CMS 12, the server returns both old and new landing pages randomly after the update. We tested this in multiple machines using different tools. The new redirects will reflect only after couple of hours. 
 
It seems like the updated redirection is not published to all server instances instantly resulting in inconsistent redirects. There was a comment from Optimizely support team that the NotFound plugin may not have implemented object cache correctly, causing the cached redirections to be different across load balanced instances. This issue is currently causing inconsistent redirects.

**Comment by marisks** [comment]
Which version of the package do you use?

**Comment by Anish-Peethambaran** [comment]
> Which version of the package do you use?

version 1.0.4

**Comment by marisks** [comment]
The latest version is 4.0.0. you should use it.

**Comment by Anish-Peethambaran** [comment]
> The latest version is 4.0.0. you should use it.

Okay. I will upgrade and see if it works. Many thanks for your suggestion.
