### ISSUE TITLE
Problem installing from optmizely nuget feed

### ISSUE THREAD

**Issue by karl-sjogren** [Geta/geta-notfoundhandler#52]
Hi,

Since yesterday we are having problems installing this package from nuget.optmizely.com. The main package is fine but when it tries to get the admin package we see an error page (which makes nuget fail and stop the process instead of trying to retrieve it from nuget.org).

The install says the url below fails.

https://api.nuget.optimizely.com/v3/package/geta.notfoundhandler.admin/index.json

If I browse to it I get this page.

![image](https://user-images.githubusercontent.com/875092/197703877-44bd83d7-3d51-48c2-9bbe-377f3db9266d.png)

Other packages works fine though, even other packages that doesn't exist work fine. It is the same error when trying locally or from our build agent on Azure DevOps.

Has the admin package been uploaded to nuget.optimizely.com recently but isn't published or something? If not, could we maybe have it published there as well so we can get all the packages from the same feed?

**Comment by marisks** [comment]
We are working on this together with Optimizely. The new package will be released today.

**Comment by valdisiljuconoks** [comment]
Please use v5.0 - https://api.nuget.optimizely.com/packages/geta.notfoundhandler.optimizely/5.0.0
