### ISSUE TITLE
New redirects do not work on CMS 12 / DXP

### ISSUE THREAD

**Issue by davidstroem** [Geta/geta-notfoundhandler#62]
We have a multi site / multi language instance on Optimizely DXP running .net 6, CMS 12 and with GETA NotFoundHandler version 5.0.1 installed.
On the prod instance we experience that new redirects are not working as expected. Instead of redirecting to the specified url we see our 404 page. 
We have experienced this in a previous version where the redirect cache where not updated on other app instances.
I am not sure this is the same issue. It might be.
Older redirects works as expected

**Comment by davidstroem** [comment]
Update. After a good nights sleep, the redirects created yesterday seem to work now. So I am leaning towards some slow cache updates for different instances.
Or maybe the instances where shut down because of no load and restarted this morning.
We also uploaded a large amount of redirects this morning, and only after a restart of the application in DXP, the redirects works.

**Comment by marisks** [comment]
NotFoundHandler is using Optimizely's `IEventRegistry` to sync between instances. I do not have any project on DXP and on multiple instances so I am not sure that it works though. According to documentation, it should work.

**Comment by davidstroem** [comment]
It seems that we didn't see the forest from all the trees. The configuration changed from the earlier version we used to 5.0.1. We didn't see that.
I am closing this issue.
