### ISSUE TITLE
nuget package conflict between Geta.NotFoundHandler.Admin and Geta.Optimizely.Tags

### ISSUE THREAD

**Issue by dgutman993** [Geta/geta-notfoundhandler#64]
recently updated all my packages to the latest and now im getting the following error in the cms
![image](https://user-images.githubusercontent.com/71526573/205758800-f5e6ef44-78e5-48d9-af3b-6a01c414c29f.png)

it looks like its caused by Pager used in this file:  /[src](https://github.com/Geta/geta-notfoundhandler/tree/master/src)/[Geta.NotFoundHandler.Admin](https://github.com/Geta/geta-notfoundhandler/tree/master/src/Geta.NotFoundHandler.Admin)/[Areas](https://github.com/Geta/geta-notfoundhandler/tree/master/src/Geta.NotFoundHandler.Admin/Areas)/[GetaNotFoundHandlerAdmin](https://github.com/Geta/geta-notfoundhandler/tree/master/src/Geta.NotFoundHandler.Admin/Areas/GetaNotFoundHandlerAdmin)/[Pages](https://github.com/Geta/geta-notfoundhandler/tree/master/src/Geta.NotFoundHandler.Admin/Areas/GetaNotFoundHandlerAdmin/Pages)/Index.cshtml

Has anyone else found a solution for this?

**Comment by ggroot** [comment]
Yes, I'm also running into the same issue here using the latest Geta nugets

![image](https://user-images.githubusercontent.com/914384/206421465-f3017f19-e822-495e-b368-c5c5071c24bc.png)

**Comment by dgutman993** [comment]
when will this fix be released?

**Comment by marisks** [comment]
I have uploaded new packages with the fix. Have to wait until Nuget.org and Optimizely will release it.
