### ISSUE TITLE
Unable to move or copy pages in CMS

### ISSUE THREAD

**Issue by davidstroem** [Geta/geta-notfoundhandler#70]
CMS 12, DXP, multisite, multi language

We have enabled automatic redirects on our multisite, multi language setup in DXP. However when we do that we are unable to move or copy pages. 
We get the error below when we copy/paste a page:
"10.5.3 Export/import error: [Importing content 92940_264303] Exception: Unterminated string. Expected delimiter: ". Path '[21].Type', line 1, position 2000.
      Newtonsoft.Json.JsonReaderException: Unterminated string. Expected delimiter: ..."

We get the below error on startup:
"Job Geta.NotFoundHandler.Optimizely.Core.AutomaticRedirects.RegisterMovedContentRedirectsJob failed for the job '[Geta NotFoundHandler] Register content move redir' with jobId ='ec96abee-5da4-404f-a0c8-451c77ca4983'
      Newtonsoft.Json.JsonReaderException: Unterminated string. ..."

It looks like the value in the Urls column in table [NotFoundHandler.ContentUrlHistory] is too large for the column so the entire serialized object is not saved correctly.

This means that we cannot use automatic redirects at the moment.

**Comment by marisks** [comment]
Hi! Thanks for reporting this. I think I know what the issue is. The column in DB is fine, the issue is with query params. I'll fix it.
