### ISSUE TITLE
Redirects created to recycle bin

### ISSUE THREAD

**Issue by karl-sjogren** [Geta/geta-notfoundhandler#71]
We have an issue where pages sent to the recycle bin gets redirects created for them to the recycle bin. I had a sample page at the url `/sv/testsida` which I threw in the recycle bin and then a redirect was added to `/sv/Recycle-Bin/testsida`.

![image](https://user-images.githubusercontent.com/875092/213135923-b8a34be5-0d7f-4e77-a843-d3959e89c862.png)

When I browse to the old url I get a 404 page as expected, but the user is first redirected to `/sv/Recycle-Bin/testsida` which looks really bad.

Is this expected behaviour? If so, is there any way for me to filter out these urls since we don't want them?

**Comment by marisks** [comment]
It seems that this is a place to filter out based on destination:
https://github.com/Geta/geta-notfoundhandler/blob/master/src/Geta.NotFoundHandler.Optimizely/Core/AutomaticRedirects/RedirectBuilder.cs#L24

How one can understand that it is a recycle bin? Just by name in a URL?
Or maybe better create a configuration that will ignore redirects to certain paths (probably by regex)?

**Comment by ellinge** [comment]
Ignoring the Enqueue here perhaps:
https://github.com/Geta/geta-notfoundhandler/blob/7e370122c5fc88ed7fe379cbb83d24cd71434b0c/src/Geta.NotFoundHandler.Optimizely/Core/AutomaticRedirects/ContentUrlHistoryEvents.cs#L41

e.TargetLink.CompareToIgnoreWorkID(ContentReference.WasteBasket)

**Comment by marisks** [comment]
Checking for TargetLink on the move event sounds like a good option. Are there other invalid destinations?
If only the waste basket is, then this would fix the issue.

**Comment by karl-sjogren** [comment]
Not that I can think of, though I'm still building my first site from scratch with Optimizely CMS so someone else might have a better idea about it.

**Comment by GeekInTheNorth** [comment]
I can only think of the Waste Basket / Recycle Bin being the main issue here.  I've temporarily disabled automatic redirect generation for now on the projects I have in flight.
