### ISSUE TITLE
How disable NotFoundHandler on virtual paths? 

### ISSUE THREAD

**Issue by LucGosso** [Geta/geta-notfoundhandler#8]
Hi @marisks this looks good, so wanted to take NotFoundHandler on a testdrive. 

BUT we are using https://github.com/ligershark/WebOptimizer for CSS and Javascript bundling. 

We do register weboptimizer like this

`services.AddWebOptimizer(pipeline =>
{
pipeline.AddCssBundle("/css/bundle.css", "/**/*.css");
pipeline.AddJavaScriptBundle("/js/bundle.js", "js/**/*.js");
});`

![image](https://user-images.githubusercontent.com/9716195/143565436-39b48cb4-fa38-4179-a0fb-1b44f137150e.png)

Seems when we installed NotFoundHandler this stopped to work, is the NotFoundHandler hijacking the pipeline somehow? When we remove the AddNotFoundHandler the css bundling is working, any idea?

**Comment by marisks** [comment]
It is just a Razor library with default ASP.NET config. No special treatment was done.
You might try to ignore the NotFoundHandler script and CSS:
/_content/Geta.NotFoundHandler.Admin/css/dashboard.css
/_content/Geta.NotFoundHandler.Admin/js/dashboard.js

**Comment by haugsten** [comment]
We have the same problem with the NotFoundHandler and WebOptimizer.
We have verified that by removing the module bundles work as before.

![image](https://user-images.githubusercontent.com/6928826/150329322-0eb4c59e-83a9-4026-b5b7-472870ecb595.png)

**Comment by LucGosso** [comment]
have you tryed with the latest version of weboptimizer? @haugsten it seems they might have fixed it in weboptimizer ... https://github.com/ligershark/WebOptimizer.Sass/issues/34 (i havent got the time to test)

**Comment by haugsten** [comment]
We are using WebOptimizer.Core and latest version does not fix the problem. But we where able fix the problem by moving the resources outside wwwroot folder and use .UseContentRoot() extension.

`                 pipeline.AddCssBundle("/static/css/bundle.css",
                    "Static/css/bootstrap.min.css",
                    "Static/css/styles.min.css").UseContentRoot();`

**Comment by oyvindwh** [comment]
@marisks In the public static IServiceCollection AddOptimizelyNotFoundHandler you are calling this services.AddCmsUI(); What is the reason for this? This will be done by Optimizely and not handled by the module?

**Comment by marisks** [comment]
@oyvindwh The code for module initialization was taken from the Optimizely example. Probably early versions needed this call.
Does it cause any issues? I can remove it and push new packages.

**Comment by marisks** [comment]
I have removed the call to CmsUI and published the packages.

**Comment by marisks** [comment]
Is this fixed by WebOptimizer already and we can close the issue?

**Comment by marisks** [comment]
Closing as it is WebOptimizer issue.
