### ISSUE TITLE
NotFoundHandler menu is not available within CMS

### ISSUE THREAD

**Issue by Deepa-Puranik** [Geta/geta-notfoundhandler#85]
After adding the necessary packages and configuration in StartUp file, not able to access the NotFoundHandler menu in CMS. CMS version installed is EPiServer.CMS(12.17.0) and packages installed are Geta.NotFoundHandler, Geta.NotFoundHandler.Admin and Geta.NotfoundHandler.Optimizely version 5.0.6. Added necessary configuration in appSettings.json and the custom error page is also not working.
Please help if there is any missing configuration to make it work.

**Comment by marisks** [comment]
How does your configuration look in Startup?

**Comment by Deepa-Puranik** [comment]
StartUp file 

- ConfigureServices() method:

var connectionString = this.Configuration.GetConnectionString("EPiServerDB");// Retrieve connection string here
            services.AddNotFoundHandler(o =>
            {
                o.UseSqlServer(connectionString);
                o.BufferSize = 30;
                o.ThreshHold = 5;
                o.HandlerMode = FileNotFoundMode.On;
                o.IgnoredResourceExtensions = new[] { "jpg", "gif", "png", "css", "js", "ico", "swf", "woff" };
                o.Logging = LoggerMode.On;
                o.LogWithHostname = false;
             });
services.AddOptimizelyNotFoundHandler(o =>
            {
                o.AutomaticRedirectsEnabled = true;
            });

- Configure() method:

 app.UseEndpoints(endpoints =>
            {
                endpoints.MapContent();
                endpoints.MapRazorPages();
            });
app.UseNotFoundHandler();

**Comment by marisks** [comment]
These should be the first ones in the Configure method:
    app.UseNotFoundHandler();
    app.UseOptimizelyNotFoundHandler();

**Comment by marisks** [comment]
Maybe it requires AddRazorPages in ConfigureServices

**Comment by Deepa-Puranik** [comment]
Added this line services.AddRazorPages(); in ConfigureServices. Still not able to see the handler.

**Comment by Deepa-Puranik** [comment]
Thank you, for your quick response on this. The issue got resolved.
