### ISSUE TITLE
Routing conflict 

### ISSUE THREAD

**Issue by Dandroid5000** [Geta/geta-notfoundhandler#93]
We have recently updated Optimizely packages EPiServer.CMS.Core 12.9.2 to 12.14.0 and are now getting a route conflict between our start page path ("/") and the path to add/delete a redirect "getanotfoundhandleradmin/?handler=create".

Currently we are unable to add or delete a redirect because the request is returning a 405.

Could you please rename following files to something more targeted? Geta.NotFoundHandler.Admin/Areas/GetaNotFoundHandlerAdmin/Pages/Index.cshtml
Geta.NotFoundHandler.Admin/Areas/GetaNotFoundHandlerAdmin/Pages/Index.cshtml.cs

We were able to resolve this in our testing with the following changes
<img width="788" alt="image" src="https://github.com/Geta/geta-notfoundhandler/assets/96799065/f6c207d9-2a0f-4725-9b9e-d0f9bb213938">

Thanks in advance

**Comment by Dandroid5000** [comment]
Hi, has anyone had a chance to look at this? 
Thanks in advance

**Comment by Dandroid5000** [comment]
Can anyone please help with this? Note, we have just been alerted that the same issue is present in the GETA Optimizely Sitemaps package.

**Comment by marisks** [comment]
@Dandroid5000 What areas/routing configuration do you have?
Has it been changed after upgrading from EPiServer.CMS.Core 12.9.2 to 12.14.0?

We use default ASP.NET routing and if it worked before, it should work now too unless there were changes in your project or in EPiServer.CMS.Core. Renaming the file is a workaround and not a proper fix.

**Comment by svenrog** [comment]
I tried reproducing this using Optimizely 12.9.0 and 12.14.0, single and multi-site configuration. Everything seemed to work correctly.

**Comment by Dandroid5000** [comment]
Hi @marisks , thanks so much for getting back to me. 
We are using attribute-based routing. This is a multi-site setup wherein each site is defined within an MVC area. Each page controller within each area uses a base controller that specifies the route and the area (see below).
![image](https://github.com/Geta/geta-notfoundhandler/assets/96799065/262588be-4f0b-478d-adec-f8b8882a3652)

Nothing has changed with respect to routing in our project since upgrading from EPiServer.CMS.Core 12.9.2 to 12.14.0, nothing that myself or my teammates have been able to determine anyway.

**Comment by Dandroid5000** [comment]
@svenrog
The only configuration change we have for custom View Locations is per below 
![image](https://github.com/Geta/geta-notfoundhandler/assets/96799065/b4b653c9-2b7b-47c4-9cc9-a5989812b4ae)

**Comment by Dandroid5000** [comment]
https://github.com/Geta/geta-notfoundhandler/blob/ca1f3730af6cdbdd797cc2c0d541143216e1acc5/src/Geta.NotFoundHandler.Admin/Areas/GetaNotFoundHandlerAdmin/Pages/Shared/_Layout.cshtml#L45C32-L45C32

^ this link is resolving to our HomepageController and hitting its Index.cshtml... this was not happening before.

**Comment by svenrog** [comment]
@Dandroid5000  Does adding  `asp-area="GetaNotFoundHandlerAdmin"` to the taghelpers with links work too?

**Comment by Dandroid5000** [comment]
Hi @svenrog , hi @marisks 

Thanks so much for the code fix! I look forward to testing it out when it hits the nuget feed!

Regarding the same issue in your sitemaps plugin (https://github.com/Geta/geta-optimizely-sitemaps), would you like me to raise an issue over on that repo too?

**Comment by valdisiljuconoks** [comment]
Yes, please do register there as well (it will help us to keep track of issues resolved in next version).

Thx!

**Comment by marisks** [comment]
The new package is published.
